import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { createClient } from '@hey-api/openapi-ts';
import { format } from 'prettier';

const contractUrl = new URL(
  '../../contracts/openapi/openapi.yaml',
  import.meta.url,
);
const outputUrl = new URL('../src/generated/openapi.ts', import.meta.url);
const tsconfigUrl = new URL('../tsconfig.lib.json', import.meta.url);
const generatedHeader = `/**
 * Generated by @hey-api/openapi-ts 0.99.0 from packages/contracts/openapi/openapi.yaml.
 * Do not edit this file manually. Run: pnpm nx run api-client:generate
 */
`;

async function render() {
  const temporaryDirectory = await mkdtemp(
    join(tmpdir(), 'saas-api-client-generation-'),
  );
  try {
    await createClient({
      input: fileURLToPath(contractUrl),
      output: {
        entryFile: false,
        path: temporaryDirectory,
        tsConfigPath: fileURLToPath(tsconfigUrl),
      },
      plugins: ['@hey-api/typescript'],
      logs: { file: false, level: 'silent' },
    });
    const generated = await readFile(
      join(temporaryDirectory, 'types.gen.ts'),
      'utf8',
    );
    const withoutDefaultHeader = generated.replace(
      /^\/\/ This file is auto-generated by @hey-api\/openapi-ts\r?\n\r?\n/,
      '',
    );
    return format(`${generatedHeader}${withoutDefaultHeader}`, {
      parser: 'typescript',
      endOfLine: 'lf',
      singleQuote: true,
    });
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

const first = await render();
const second = await render();
if (first !== second) {
  throw new Error('OpenAPI TypeScript generation is not deterministic.');
}

if (process.argv.includes('--check')) {
  let current;
  try {
    current = await readFile(outputUrl, 'utf8');
  } catch (error) {
    if (error?.code === 'ENOENT') {
      throw new Error(
        'Generated API types are missing. Run pnpm nx run api-client:generate.',
      );
    }
    throw error;
  }
  if (current !== first) {
    throw new Error(
      'Generated API types are stale. Run pnpm nx run api-client:generate.',
    );
  }
  console.log('Generated API types are deterministic and current.');
} else {
  await mkdir(dirname(fileURLToPath(outputUrl)), { recursive: true });
  await writeFile(outputUrl, first, 'utf8');
  console.log(`Generated ${fileURLToPath(outputUrl)}.`);
}
