export const PLATFORM_AUDIT_ACTIONS = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  PERMISSION_CHANGED: 'PERMISSION_CHANGED',
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
} as const;

export type PlatformAuditAction =
  (typeof PLATFORM_AUDIT_ACTIONS)[keyof typeof PLATFORM_AUDIT_ACTIONS];
